### ISSUE TITLE
Version field warning in opam

### ISSUE THREAD

**Issue by LucaFranceschini** [thvnx/mlmpfr#2]
```
[WARNING] At /home/luca/.opam/repo/default/packages/mlmpfr/mlmpfr.4.0.0/opam:3:0:
          This file is for version '4.0.0' but its 'version:' field advertises '4.0.x'.
```

I don't know much about opam file syntax but I guess '4.0.x' is not a valid syntax and the `version` field should contain an exact version number?

**Comment by thvnx** [comment]
Thanks for reporting this!

It will be fixed in a next release of mlmpfr's opam files. I guess that renaming the package folder from `mlmpfr.4.0.0` to `mlmpfr.4.0.x` should be enough. Otherwise, I will fix this by providing one opam file for each mlmpfr.4.0.[0-2] versions.

**Comment by LucaFranceschini** [comment]
Due to [opam version order](https://opam.ocaml.org/doc/Manual.html#version-ordering), `4.0.x < 4.0.0` would hold, which does not seem to be correct in your case.

I'm not sure it makes sense for version fields to contain version ranges than exact versions.

**Comment by thvnx** [comment]
OK! I will consider to publish one opam file per mlmpfr version.

**Comment by thvnx** [comment]
Changes have been merged to opam-repository. Thanks again!
