### ISSUE TITLE
Compatibility with MPFR 4.2.0

### ISSUE THREAD

**Issue by Mavaxavou** [thvnx/mlmpfr#28]
Would it be possible to make this package compatible with MPFR 4.2.0 ? I've seen some commits pushing in that direction but the compatibility test still rejects other versions than 4.1.1, which is problematic on an updated ArchLinux for example.

**Comment by thvnx** [comment]
Hi, I'm working on the 4.2.0 upgrade but I can't give it much time at the moment. However, I can push at least an update on opam to make the latest version compatible with 4.2.0! I'll work on that this weekend!

**Comment by thvnx** [comment]
Hi @Mavaxavou , you should now be able to install the latest mlmpfr version on a system that comes with mpfr 4.2.0. Let me know if that's not the case.

I'll improve version management in the future version of mlmpfr.

Thanks!
