### ISSUE TITLE
Opam version is limited to MPFR 4.1.1

### ISSUE THREAD

**Issue by Mavaxavou** [thvnx/mlmpfr#34]
Hi. The latest version on opam is still tailored to MPFR 4.1.1. I know `master` is now compatible with the latest versions, would it be possible to release it on opam please ?

**Comment by thvnx** [comment]
Sure. This was on my todo list. I'll work on it!

**Comment by thvnx** [comment]
Work in progress, PRs opened: ocaml/opam-repository#24977 and ocaml/opam-repository#24978

**Comment by thvnx** [comment]
PRs have been merged, 4.2.0 and 4.2.1 will be available via opam soon!
