### ISSUE TITLE
Incorrect precision bounds

### ISSUE THREAD

**Issue by bksaiki** [thvnx/mlmpfr#37]
MPFR documentation on precision says
> The precision can be any integer between MPFR_PREC_MIN and MPFR_PREC_MAX

However, MPFR_PREC_MIN is not a valid precision in the current implementation.

https://github.com/thvnx/mlmpfr/blob/a356c25136c836db47da495329eb8464f332aecf/src/mlmpfr_stubs.c#L36-L45

**Comment by thvnx** [comment]
Hi @bksaiki , thanks for reporting this! I just pushed a fix in master.

**Comment by bksaiki** [comment]
Great. Thanks for the quick reply!
